version: '2'
services:
  db:
    image: postgres:9.4.1
  ui:
    build: ./moveit-ui/
    volumes:
      - ./moveit-ui/dist:/usr/share/nginx/html
    ports:
      - "9000:80"

  api:
    build: ./moveit-api/
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./moveit-api:/app

